### ISSUE TITLE
Analysis Presentation

### ISSUE THREAD

**Issue by bakert14** [S18MIS4173Team3/Team3#1]
Due Tuesday 2/13/18

**Comment by Looneys14** [comment]
[Add Stakeholder Use Case.docx](https://github.com/S18MIS4173Team3/Team3/files/1700215/Add.Stakeholder.Use.Case.docx)

**Comment by bakert14** [comment]
https://docs.google.com/presentation/d/1_POFpDIHuvnQ0cOrBsTgchaeg4co6SBzrV-1YNIWrmM/edit#slide=id.g3332a198d9_0_12
