### ISSUE TITLE
Mock-ups

### ISSUE THREAD

**Issue by bakert14** [S18MIS4173Team3/Team3#10]
This is Forms and reports. Prototypes form VB or html

**Comment by Looneys14** [comment]
![login menu](https://user-images.githubusercontent.com/35345588/37434493-2134ba96-27b6-11e8-9ad6-c65e6527af16.PNG)

**Comment by Looneys14** [comment]
![fowl menu scree](https://user-images.githubusercontent.com/35345588/37434765-2380d216-27b7-11e8-8000-29ffe6c957a4.PNG)

**Comment by Looneys14** [comment]
![customer management screen](https://user-images.githubusercontent.com/35345588/37435417-93cea44c-27b9-11e8-9e8c-dbe263d2d831.PNG)
![employee managment](https://user-images.githubusercontent.com/35345588/37435418-93f96e66-27b9-11e8-9f67-b6620587d30d.PNG)
![inventory management screen](https://user-images.githubusercontent.com/35345588/37435419-9418dab2-27b9-11e8-898f-4d3372400b50.PNG)

**Comment by Looneys14** [comment]
![new customer management](https://user-images.githubusercontent.com/35345588/37480638-2104b288-2856-11e8-92bf-bf92d0f93084.PNG)
![new employee manage](https://user-images.githubusercontent.com/35345588/37480640-211dda38-2856-11e8-89a4-69c6f48d5ca8.PNG)
![new inventory management screen](https://user-images.githubusercontent.com/35345588/37480641-21294f6c-2856-11e8-8237-efdd279dcf3d.PNG)
![new login](https://user-images.githubusercontent.com/35345588/37480642-2134818e-2856-11e8-9db5-962242524411.PNG)
![new main menu](https://user-images.githubusercontent.com/35345588/37480643-213f26d4-2856-11e8-9efe-711e9f9aaa5d.PNG)
