### ISSUE TITLE
Sample Reports

### ISSUE THREAD

**Issue by bakert14** [S18MIS4173Team3/Team3#11]
Same as our mock-ups but with data

**Comment by bakert14** [comment]
[Sample Customer Report.xlsx](https://github.com/S18MIS4173Team3/Team3/files/1813352/Sample.Customer.Report.xlsx)

**Comment by tuttlem13** [comment]
[Inventory Report.xlsx](https://github.com/S18MIS4173Team3/Team3/files/1813448/Inventory.Report.xlsx)
