### ISSUE TITLE
DFD level 1

### ISSUE THREAD

**Issue by bakert14** [S18MIS4173Team3/Team3#15]

**Comment by Looneys14** [comment]
Level 0 DFD 
![level 0 dfd fowl](https://user-images.githubusercontent.com/35345588/37318231-c9494cd8-263f-11e8-8f13-13da1ca438d8.PNG)

**Comment by Looneys14** [comment]
![customer level 1 dfd](https://user-images.githubusercontent.com/35345588/37359791-e3e823ae-26c4-11e8-8b75-3d98b3c21499.PNG)
![employee level 1 dfd](https://user-images.githubusercontent.com/35345588/37359792-e3f91632-26c4-11e8-9f63-fd7b0bd148a3.PNG)
![inventory level 1 dfd](https://user-images.githubusercontent.com/35345588/37359793-e40a70d0-26c4-11e8-98d3-98fcfa199649.PNG)

**Comment by Looneys14** [comment]
![customer level 1 dfd](https://user-images.githubusercontent.com/35345588/37495797-77f2f60c-2885-11e8-8128-060fb91884c6.PNG)
![employee level 1 dfd](https://user-images.githubusercontent.com/35345588/37495798-7803bca8-2885-11e8-9509-d95c9fe742d0.PNG)
![inventory level 1 dfd](https://user-images.githubusercontent.com/35345588/37495799-7812d300-2885-11e8-8f9b-6811369502d6.PNG)
