### ISSUE TITLE
Use Cases

### ISSUE THREAD

**Issue by bakert14** [S18MIS4173Team3/Team3#2]

**Comment by bakert14** [comment]
[UseCase Inventory Report.docx](https://github.com/S18MIS4173Team3/Team3/files/1700212/UseCase.Inventory.Report.docx)
[UseCase Login.docx](https://github.com/S18MIS4173Team3/Team3/files/1700213/UseCase.Login.docx)
[UseCase Customer Report.docx](https://github.com/S18MIS4173Team3/Team3/files/1700214/UseCase.Customer.Report.docx)

**Comment by tuttlem13** [comment]
[Use Case Rough Draft.docx](https://github.com/S18MIS4173Team3/Team3/files/1700217/Use.Case.Rough.Draft.docx)

**Comment by Looneys14** [comment]
[Add Stakeholder Use Case.docx](https://github.com/S18MIS4173Team3/Team3/files/1700223/Add.Stakeholder.Use.Case.docx)

**Comment by shifflettr13** [comment]
[Modify Delete Customer Information.docx](https://github.com/S18MIS4173Team3/Team3/files/1700226/Modify.Delete.Customer.Information.docx)

[Manage Invetory Use Case.docx](https://github.com/S18MIS4173Team3/Team3/files/1700224/Manage.Invetory.Use.Case.docx)
[Access Inventory.docx](https://github.com/S18MIS4173Team3/Team3/files/1700222/Access.Inventory.docx)

**Comment by bakert14** [comment]
[Use case order and notes.txt](https://github.com/S18MIS4173Team3/Team3/files/1707344/Use.case.order.and.notes.txt)


Hey guys- here is the order for use cases. As they are all still in the rough draft format we need to look at the suggestions and start reevaluating what we need to put together and what each use case needs to accomplish.

**Comment by tuttlem13** [comment]
[UseCase (Seeman template).docx](https://github.com/S18MIS4173Team3/Team3/files/1708216/UseCase.Seeman.template.docx)

**Comment by shifflettr13** [comment]
[Manage Invetory Use Case.docx](https://github.com/S18MIS4173Team3/Team3/files/1708509/Manage.Invetory.Use.Case.docx)
[Modify Delete Customer Information.docx](https://github.com/S18MIS4173Team3/Team3/files/1708510/Modify.Delete.Customer.Information.docx)

**Comment by tuttlem13** [comment]
[UseCase (Seeman template).docx](https://github.com/S18MIS4173Team3/Team3/files/1709199/UseCase.Seeman.template.docx)
This is my updated/final use case

**Comment by bakert14** [comment]
[UseCase Inventory Report.docx](https://github.com/S18MIS4173Team3/Team3/files/1709202/UseCase.Inventory.Report.docx)
[UseCase Customer Report.docx](https://github.com/S18MIS4173Team3/Team3/files/1709203/UseCase.Customer.Report.docx)
[UseCase Login.docx](https://github.com/S18MIS4173Team3/Team3/files/1709204/UseCase.Login.docx)

**Comment by shifflettr13** [comment]
[Modify Delete Customer Information.docx](https://github.com/S18MIS4173Team3/Team3/files/1712437/Modify.Delete.Customer.Information.docx)
[Manage.Invetory.Use.Case.docx](https://github.com/S18MIS4173Team3/Team3/files/1712439/Manage.Invetory.Use.Case.docx)

**Comment by Looneys14** [comment]
[Add.Stakeholder.Use.Case.docx](https://github.com/S18MIS4173Team3/Team3/files/1712459/Add.Stakeholder.Use.Case.docx)

**Comment by bakert14** [comment]
[USE CASES COMPLETE.docx](https://github.com/S18MIS4173Team3/Team3/files/1718309/USE.CASES.COMPLETE.docx)


Completed Use cases

**Comment by bakert14** [comment]
[USE CASES COMPLETE.docx](https://github.com/S18MIS4173Team3/Team3/files/1718329/USE.CASES.COMPLETE.docx)


Completed use cases

**Comment by bakert14** [comment]
[USE CASES COMPLETE.docx](https://github.com/S18MIS4173Team3/Team3/files/1718330/USE.CASES.COMPLETE.docx)

Completed Use Cases
