### ISSUE TITLE
Proposed Navigation Diagram

### ISSUE THREAD

**Issue by bakert14** [S18MIS4173Team3/Team3#4]

**Comment by bakert14** [comment]
[Navigation Diagram.docx](https://github.com/S18MIS4173Team3/Team3/files/1804047/Navigation.Diagram.docx)

**Comment by bakert14** [comment]
[Navigation Diagram.docx](https://github.com/S18MIS4173Team3/Team3/files/1804081/Navigation.Diagram.docx)

**Comment by Looneys14** [comment]
![navigation diagram](https://user-images.githubusercontent.com/35345588/37373715-26d3d1c6-26ee-11e8-89c3-c78fa7e9f86c.PNG)

**Comment by Looneys14** [comment]
[Blank Diagram (1).pdf](https://github.com/S18MIS4173Team3/Team3/files/1808911/Blank.Diagram.1.pdf)
