### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by bakert14** [S18MIS4173Team3/Team3#8]

**Comment by tuttlem13** [comment]
[Inventory ERD.pdf](https://github.com/S18MIS4173Team3/Team3/files/1807509/Inventory.ERD.pdf)

**Comment by tuttlem13** [comment]
[Customer ERD.pdf](https://github.com/S18MIS4173Team3/Team3/files/1807582/Customer.ERD.pdf)

**Comment by shifflettr13** [comment]
[ERD (1).pdf](https://github.com/S18MIS4173Team3/Team3/files/1813366/ERD.1.pdf)

**Comment by shifflettr13** [comment]
[ERD (2).pdf](https://github.com/S18MIS4173Team3/Team3/files/1813431/ERD.2.pdf)

**Comment by shifflettr13** [comment]
[ERD (4).pdf](https://github.com/S18MIS4173Team3/Team3/files/1817316/ERD.4.pdf)
