### ISSUE TITLE
Detailed Non-functional Requirements

### ISSUE THREAD

**Issue by bakert14** [S18MIS4173Team3/Team3#9]
This includes logic

**Comment by tuttlem13** [comment]
[Detailed Non-Functional Requirements.docx](https://github.com/S18MIS4173Team3/Team3/files/1803349/Detailed.Non-Functional.Requirements.docx)

**Comment by tuttlem13** [comment]
[Detailed Non-Functional Requirements.docx](https://github.com/S18MIS4173Team3/Team3/files/1808797/Detailed.Non-Functional.Requirements.docx)
